quarkus:
  datasource:
    cust:
      db-kind: mysql
    admin:
      db-kind: mysql
  hibernate-orm:
    admin:
      datasource: admin
      packages: [ ac.me.entity.admin ]
#      dialect: org.hibernate.dialect.MySQL57Dialect
    cust:
      multitenant: DATABASE
      datasource: cust
      packages: ac.me.entity.cust
#      dialect: org.hibernate.dialect.MySQL57Dialect
