quarkus:
  datasource:
    cust:
      db-kind: postgresql
    admin:
      db-kind: postgresql
  hibernate-orm:
    admin:
      database:
        generation: none
      multitenant: DATABASE
      datasource: admin
      packages: ac.me.entity.admin
    cust:
      database:
        generation: none
      multitenant: DATABASE
      datasource: cust
      packages: ac.me.entity.cust
  flyway:
    cust:
      locations: classpath:database/cust
      migrate-at-start: true
    admin:
      locations: classpath:database/admin
      migrate-at-start: true
